apiVersion: apps/v1
kind: Deployment
metadata:
  name: logsv-server
  labels:
    app: logsv-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logsv-server
  template:
    metadata:
      labels:
        app: logsv-server
    spec:
      containers:
      - name: logsv-server
        image: logsv/logsv:latest
        ports:
        - containerPort: 3001
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: logsv-service
spec:
  selector:
    app: logsv-server
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  - name: websocket
    port: 8080
    targetPort: 8080
  type: LoadBalancer
